### PR TITLE
Create interface from type to improve the testability of this library

### PR DESCRIPTION
**Pull request by nikolaistraessle**
It is very hard to test the usage of this library in other projects.

With these interfaces, it will be easy to mock this library.

When developing other projects, the functionality of external libraries should not have to be tested as well.

### CODE REVIEW

**Comment by jlinnosa** [comment]
In your latest commit you have capitalized every instance on the string `file`... This seems wrong.

**Comment by nikolaistraessle** [comment]
@jlinnosa thanks you're right. Only the struct type `File` should be capitalized and exported, but not the comments. I've fixed this.

**Comment by nikolaistraessle** [comment]
@jlinnosa thanks you're right. Only the struct type `File` should be capitalized and exported, but not the comments. I've fixed this.

**Comment by xhit** [comment]
Hi, thanks for the PR, I have some questions:

- Why change `file` struct to public when all fields aren't?
- Why interfaces? I think is a tool to solve some problems when you have a lot of internal packages in a package, and this is simple.
- Why copy value instead pass pointer? Maybe can be fast but eat resources. This package was created to solve a problem. And now we have a EC2 linux with 1 core and 1 GB RAM sending ~1000 mails/seconds (not spam) easily. I only will accept a refactor like this if performance is equal or better (avoiding unsafe package). So you can add some benchmarks and we will re-considerate this breaking change for another major version.

Also, I'm not a developer, I 'm a tech support that create tools for some problems, so any mistake I said please show me, I like to learn.

**Comment by nikolaistraessle** [comment]
Hi @xhit 

Thanks for your questions. Below my answers:

- The struct `File` should be exported because it is a return type of some interface methods. Code of other projects should know the definition of this type.
- With these interfaces it is possible to generate mocks for the logic of this package. If I can't mock this application, other projects have to build a test mail server to create unit tests. This takes some time and contradicts the concept of unit tests. In a unit test, only the self-written code should be tested, otherwise it is an integration test.
- I will revise this part again

Best regards

**Comment by xhit** [comment]
> With these interfaces it is possible to generate mocks for the logic of this package. If I can't mock this application, other projects have to build a test mail server to create unit tests. This takes some time and contradicts the concept of unit tests. In a unit test, only the self-written code should be tested, otherwise it is an integration test.

It's possible unit test the email.

The smtp_test.go have test for SMTP, and to unit test email it's possible to create the message, and check if the RFC822 formatted message returned with `GetMessage` method is the expected. That message can be send with any SMTP library.

**Comment by nikolaistraessle** [comment]
> It's possible unit test the email.
> 
> The smtp_test.go have test for SMTP, and to unit test email it's possible to create the message, and check if the RFC822 formatted message returned with `GetMessage` method is the expected. That message can be send with any SMTP library.

Yes, I know that this is possible. But per definition a unit test should only test the own written piece code. If a developer uses a library like this package, the code of this package should not be tested because a developer has no influence on code in external packages. If I implement for example the function `email.Send()` a valid connection to a smtp server (of course, that can be an httptest-server) must be existing. If there is no valid connection, it is not possible to test the own written code without receiving an error. And with a valid connection, it is no longer a pure unit test, it is an integration test.

With interfaces, the called functions of a library can be mocked and no connections or other bindings are needed for pure unit tests.

**Comment by xhit** [comment]
Well, I didn't expect others try to unit test in that form.

I expected the tests to be:

- get the message and validate it
- send the mail to a mock server

And, with this way, it's possible write a good unit test in this package, because there is a  mock smtp server in smtp_test.go.

Like I say, I'm open to do a breaking change with this if it's to help developer testing, but only if performance is equal or better because we have customers using this with very minimal hardware requirements.

I want to test the performance in the full project using this package, but I can't now cause IT, maybe next week.

**Comment by xhit** [comment]
Hello, I will close it. It's time to V3 so make all your ideas here: https://github.com/xhit/go-simple-mail/discussions/53

Any breaking change feature will be received too.

**Pull request closed without merging**
