### PR TITLE
Auto detect authentication type

### PR DESCRIPTION
**Pull request by utkarshmani1997**

### CODE REVIEW

**Comment by utkarshmani1997** [comment]
@xhit could you please review?

**Comment by xhit** [comment]
Hi, thanks for the contribution!

This is a breaking change, so, I cannot merge this on master now, can be used in v3 branch, but I prefer another implementation: to add another `AuthType` called `AuthAuto` and set as default.

If `AuthAuto` is specified, call your implementation. This will be useful to users that will test custom SMTP servers (I have one that depending the `AuthType` less memory is used, also I need to test different behaviors depending the `AuthType`).

With this, current implementation will be available.

**Comment by utkarshmani1997** [comment]
Sounds good. I have addressed your concerns in the new commit.

**Comment by utkarshmani1997** [comment]
@xhit could you please review ?

**Comment by xhit** [comment]
Hi, I expect review this today

Thanks

**Comment by xhit** [comment]
Merged, thanks for contribution!

**Comment by utkarshmani1997** [comment]
Thank you

**Pull request merged**
