### PR TITLE
Allow to add inplace in-memory data

### PR DESCRIPTION
**Pull request by falconandy**
I can't use files in some environment - the file system is read-only.

### CODE REVIEW

**Comment by xhit** [comment]
Hi, thanks for PR!

Your implementation only add support for inline data but not for complete attachments.

It's this PR WIP?

**Comment by falconandy** [comment]
Hi! There is `AddAttachmentBase64` method that can be used for in-memory attachments. Personally I would add more general method `AddAttachmentData(data []byte, filename, mimeType string)`. Maybe single method `AddAttachmentData(data []byte, inline bool, filename, mimeType string)` can be used instead of both.

**Comment by xhit** [comment]
`AddAttachmentBase64` is used when you have a service that send an base64 string that need to be attached in email.

I like the `AddAttachmentData(data []byte, filename, mimeType string)` and have an optional unexported function to add if inline or not like  `attachData(data []byte, inline bool, filename, mimeType string)` called by `AddAttachmentData` and `AddInlineData`.

I'm glad to accept your PR after these new features added. If you have time you can add them. If you don't have time, I will add these changes to your repo in next days.

Thanks! Interesting and good feature.

**Comment by falconandy** [comment]
Added!

**Comment by xhit** [comment]
I will review this ASAP. Thanks!

**Comment by xhit** [comment]
LGTM. Good job.

**Comment by falconandy** [comment]
@xhit Could you please add a new tag to allow use latest version with Go modules? Thank you.

**Comment by xhit** [comment]
It's new, so v2.6.0 will be released.

**Pull request merged**
