### PR TITLE
Add golangci-lint action

### PR DESCRIPTION
**Pull request by alex1989hu**
Add golangci-lint action

Use permissive configuration to ease follow up
of changes, fixes reported by the linter

Applied fixes:
- Fix deadcode, unused and varcheck lint errors
- Fix govet lint errors

Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

### CODE REVIEW

**Comment by xhit** [comment]
Hi.

I don't want to maintain a configuration file. I will merge this only if community can maintain that linter configuration file. Are you agreed?

**Comment by alex1989hu** [comment]
> Hi.
> 
> I don't want to maintain a configuration file. I will merge this only if community can maintain that linter configuration file. Are you agreed?

Hello, the configuration file is compatible with the configured `golangci-lint` version. It does not need any maintain task until somebody wants to enable new linter and/or upgrade `golangci-lint` itself. I did not want to enable all linters, fix issues etc. due to keep the commit small as possible.

**Comment by xhit** [comment]
I got it. Please fix conflicts before merge. Thanks.

**Comment by alex1989hu** [comment]
> I got it. Please fix conflicts before merge. Thanks.

Rebased onto current `master` branch; also upgraded `golangci-lint` version.

**Pull request merged**
