### PR TITLE
Changed Encryption type to be public so the value can be passed around.

### PR DESCRIPTION
**Pull request by yene**

### CODE REVIEW

**Comment by xhit** [comment]
Hi, thanks for the PR!

What issue can resolve this? I can understand that SMTP Client and SMTP Message can be built with struct instead methods, I'm right? If yes, maybe the complete functionality should be implemented instead only for Encryption.

**Comment by yene** [comment]
Dear spiderman,
https://github.com/yene/go-cronic/blob/master/main.go#L149

**Comment by xhit** [comment]
But `encryption` type is `int`, with this change the value need to be passed like int.

How do you want pass the value? Like `int` or `string`?

Can you give me an example code with implementation that you want?

**Comment by xhit** [comment]
Thanks for your PR!

**Pull request merged**
