### PR TITLE
Rfc1870 fix

### PR DESCRIPTION
**Pull request by norguhtar**
As i'm see client not support SIZE as expected. I add message SIZE as it described in RFC 1870. 

Can you check my propose for extend mail command in smtp.go ? I also need this extensions 

- CHECKPOINT RFC 1845
- BINARYMIME RFC 3030
- CHUNKING   RFC 3030

CHECKPOINT also need extend *mail from* command like this PR for size

And CHUNKING and BINARYMIME need additional command and disable break commands on lines limit by 80

### CODE REVIEW

**Comment by xhit** [comment]
Hi. Thanks for PR!

Please fix smtp_test.go to add only the changes and not the whole file.

The conflict was only because line endings changed to LF from CRLF.

**Comment by norguhtar** [comment]
Hmm. Strange. But only this file have CRLF. Other files contain LF. I think we shold fix this issue.

**Comment by norguhtar** [comment]
Any way i fixed it.

**Comment by xhit** [comment]
To fix this:

- Convert smtp_test.go to LF
- Merge current master into rfc1870-fix

I fixed locally but I don have access to add changes in your branch.

**Comment by norguhtar** [comment]
Okey. I convert to LF and merge master in my branch

**Comment by xhit** [comment]
Tested. Thanks! for your PR!

**Pull request merged**
